### ISSUE TITLE
Nothing generated

### ISSUE THREAD

**Issue by nkh** [kal247/App-bookmarks#7]
"bookmarks"  find out that I am using chrome open the bookmarks files (according to strace) and then nothing is generated, no output on stdout nor file create (the documentation says nothing about what and where is generated) and exists with an error code.

**Comment by kal247** [comment]
There's no file output, only stdout.
If no bookmark exists (in the chrome "Bookmarks" file), then nothing is
printed out to stdout/stderr.
The file you see open : is it really your Bookmarks file (and not some
default profile/location)?
It should be encoded as UTF-8 (I don't know if Chrome supports other
encodings).
What OS and Chrome version do you have?
